import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Rectangle;

import javax.swing.*;
import javax.swing.border.Border;
public class Finestra {
	JFrame fin;
	JPanel top;
	JPanel mid;
	JPanel bottom;
	JLabel Sa;
	JTextArea sa;
	JLabel Port;
	JTextArea port;
	JButton con;
	JButton Discon;
	JTextArea log;
	JTextArea pdf;
	JTextArea mp3;
	JLabel Dim;
	JTextArea dim;
	JButton start;
	JButton stop;
	JButton clear;
	JScrollPane sin;
	JScrollPane cen;
	JScrollPane des;
	JPanel sx;
	JPanel cx;
	JPanel dx;
	public Finestra(){
		this.fin=new JFrame("Vittorio Cava 2047459");
		this.fin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		this.top=new JPanel();
		this.Sa=new JLabel("Server Address:");
		this.sa=new JTextArea(1,10);
		Border bsa= BorderFactory.createLineBorder(Color.BLACK);
		sa.setBorder(bsa);
		this.Port=new JLabel("Port:");
		this.port=new JTextArea(1,10);
		port.setBorder(bsa);
		this.con=new JButton("Connect");
		this.Discon=new JButton("Disconnect");
		this.top.add(Sa);
		this.top.add(sa);
		this.top.add(Port);
		this.top.add(port);
		this.top.add(con);
		this.top.add(Discon);
		this.top.setLayout(new FlowLayout());
		fin.add(top,BorderLayout.NORTH);
		this.mid=new JPanel();
		this.log=new JTextArea(11,15);
		this.log.setEditable(false);
		this.sin=new JScrollPane(this.log);
		this.pdf=new JTextArea(11,15);
		this.pdf.setEditable(false);
		this.cen=new JScrollPane(this.pdf);
		this.mp3=new JTextArea(11,15);
		this.mp3.setEditable(false);
		this.des=new JScrollPane(this.mp3);
		Border b1= BorderFactory.createTitledBorder("Log");
		sin.setBorder(b1);
		Border b2= BorderFactory.createTitledBorder(".pdf");
		cen.setBorder(b2);
		Border b3= BorderFactory.createTitledBorder(".mp3");
		des.setBorder(b3);
		mid.setLayout(new FlowLayout());
		mid.add(sin);
		mid.add(cen);
		mid.add(des);
		fin.add(mid,BorderLayout.CENTER);
		this.bottom=new JPanel();
		this.Dim=new JLabel("Dimensione:");
		this.dim=new JTextArea(1,10);
		this.dim.setOpaque(false);
		Border bdim= BorderFactory.createLineBorder(Color.BLUE);
		this.dim.setBorder(bdim);
		this.dim.setEditable(false);
		this.start=new JButton("Start");
		this.stop=new JButton("Stop");
		this.clear=new JButton("Clear");
		bottom.setLayout(new FlowLayout());
		bottom.add(Dim);
		bottom.add(dim);
		bottom.add(start);
		bottom.add(stop);
		bottom.add(clear);
		this.Discon.setEnabled(false);
		this.start.setEnabled(false);
		this.stop.setEnabled(false);
		this.clear.setEnabled(false);
		
		fin.add(bottom, BorderLayout.SOUTH);
		fin.setVisible(true);
		fin.setSize(640,330);
		
		
	}
}
