import java.awt.*;
import javax.swing.*;
import javax.swing.border.Border;

public class Finestra {
	JFrame fin;
	JPanel top;
	JPanel cen;
	JPanel bot;
	JLabel ip;
	JTextArea Ip;
	JLabel port;
	JTextArea Port;
	JButton con;
	JButton discon;
	JPanel sx;
	JTextArea SX;
	JPanel cx;
	JTextArea CX;
	JPanel dx;
	JTextArea DX;
	JButton start;
	JButton stop;
	public Finestra(){
		fin=new JFrame("Vittorio Cava 2047459");
		fin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		top=new JPanel();
		ip=new JLabel("IP Address");
		Ip=new JTextArea(1,7);
		port=new JLabel("Port");
		Port=new JTextArea(1,7);
		con=new JButton("Connect");
		discon=new JButton("Disconnect");
		top.setLayout(new FlowLayout());
		top.add(ip);
		top.add(Ip);
		top.add(port);
		top.add(Port);
		top.add(con);
		top.add(discon);
		//SX=new JTextArea(10,15);
		//SX.setBackground(Color.LIGHT_GRAY);
		sx=new JPanel();
		//sx.add(SX);
		sx.setBackground(Color.LIGHT_GRAY);
		cx=new JPanel();
		//CX=new JTextArea(10,15);
		//CX.setBackground(Color.LIGHT_GRAY);
		//cx.add(CX);
		cx.setBackground(Color.LIGHT_GRAY);
		dx=new JPanel();
		//DX=new JTextArea(10,15);
		//DX.setBackground(Color.LIGHT_GRAY);
		//dx.add(DX);
		dx.setBackground(Color.LIGHT_GRAY);
		Border b=BorderFactory.createLineBorder(Color.BLACK);
		sx.setBorder(b);
		cx.setBorder(b);
		dx.setBorder(b);
		cen=new JPanel();
		cen.setLayout(new GridLayout(1,3));
		cen.add(sx);
		cen.add(cx);
		cen.add(dx);
		start=new JButton("Start");
		stop=new JButton("Stop");
		bot=new JPanel();
		bot.setLayout(new FlowLayout());
		bot.add(start);
		bot.add(stop);
		discon.setEnabled(false);
		start.setEnabled(false);
		stop.setEnabled(false);
		fin.add(top,BorderLayout.NORTH);
		fin.add(cen,BorderLayout.CENTER);
		fin.add(bot, BorderLayout.SOUTH);
		fin.pack();
		fin.setVisible(true);
		
	}
}
